"use strict";
const langButtons=document.querySelectorAll(".lang-btn");
const textItems=document.querySelectorAll("[data-en][data-ka]");
const placeholderItems=document.querySelectorAll("[data-placeholder-en][data-placeholder-ka]");
let currentLang=localStorage.getItem("invite-language")||"ka";
function setLanguage(lang){currentLang=lang;localStorage.setItem("invite-language",lang);textItems.forEach(item=>{const text=item.getAttribute(`data-${lang}`);if(!text)return;text.includes("<br>")?item.innerHTML=text:item.textContent=text});placeholderItems.forEach(item=>{const value=item.getAttribute(`data-placeholder-${lang}`);if(value)item.placeholder=value});langButtons.forEach(btn=>btn.classList.toggle("active",btn.dataset.lang===lang));document.documentElement.lang=lang}
langButtons.forEach(btn=>btn.addEventListener("click",()=>setLanguage(btn.dataset.lang)));setLanguage(currentLang);
const introScreen=document.getElementById("introScreen");const openInvitation=document.getElementById("openInvitation");const header=document.querySelector(".site-header");const bgMusic=document.getElementById("bgMusic");const musicToggle=document.getElementById("musicToggle");let musicPlaying=false;
function updateMusicButton(){if(!musicToggle||!bgMusic)return;musicToggle.classList.toggle("playing",!bgMusic.paused);musicToggle.textContent=bgMusic.paused?"♪":"♫"}
function playMusic(){if(!bgMusic)return;bgMusic.volume=.3;bgMusic.play().then(()=>{musicPlaying=true;updateMusicButton()}).catch(()=>{musicPlaying=false;updateMusicButton()})}
openInvitation?.addEventListener("click",()=>{document.body.classList.remove("intro-locked");document.body.classList.add("experience-started");introScreen?.classList.add("opened");header?.classList.add("visible");musicToggle?.classList.add("visible");playMusic();setTimeout(()=>introScreen?.remove(),1000)});
musicToggle?.addEventListener("click",event=>{event.stopPropagation();if(bgMusic.paused)playMusic();else{bgMusic.pause();musicPlaying=false;updateMusicButton()}});updateMusicButton();
const weddingDate=new Date("2026-09-14T18:00:00+04:00").getTime();
function updateCountdown(){const distance=weddingDate-Date.now();const ids=["days","hours","minutes","seconds"];const els=ids.map(id=>document.getElementById(id));if(els.some(el=>!el))return;if(distance<=0){els.forEach(el=>el.textContent="00");return}const values=[Math.floor(distance/86400000),Math.floor(distance/3600000)%24,Math.floor(distance/60000)%60,Math.floor(distance/1000)%60];els.forEach((el,i)=>el.textContent=String(values[i]).padStart(2,"0"))}
updateCountdown();setInterval(updateCountdown,1000);
const rsvpForm=document.querySelector(".rsvp-form");const rsvpButton=rsvpForm?.querySelector("button");rsvpForm?.addEventListener("submit",event=>{event.preventDefault();const guestName=rsvpForm.elements.name.value.trim();if(!guestName){rsvpButton.textContent=currentLang==="ka"?"შეავსეთ სახელი":"Enter your name";rsvpButton.classList.add("error");setTimeout(()=>{rsvpButton.textContent=currentLang==="ka"?"გაგზავნა":"Send RSVP";rsvpButton.classList.remove("error")},1700);return}rsvpButton.textContent=currentLang==="ka"?"გაგზავნილია":"Sent";rsvpButton.classList.add("sent");setTimeout(()=>{rsvpForm.reset();rsvpButton.textContent=currentLang==="ka"?"გაგზავნა":"Send RSVP";rsvpButton.classList.remove("sent")},2200)});
const revealItems=document.querySelectorAll(".letter-inner,.polaroid,.countdown,.detail,.section-heading,.timeline-item,.recommendations-list article,.rsvp-heading,.rsvp-form");const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("show");observer.unobserve(entry.target)}}),{threshold:.12});revealItems.forEach((item,index)=>{item.classList.add("reveal");item.style.transitionDelay=`${Math.min(index%4,3)*.08}s`;observer.observe(item)});
